### ISSUE TITLE
bug: wifi/dhcp/dns problem. frequent restarts of air quality egg making it useless

### ISSUE THREAD

**Issue by PieterGit** [WickedDevice/AQEV2FW#24] opened 2015-10-11 09:49 UTC
air quality egg will not connect to the network. it fails most of the time while resoliving the mqtt server
tested with 2.0.4 firmware from GitHub (experienced it with my ntp-version as well, but can reproduce without my changes). tried both with dhcp and with static ip, no difference.

i'll sent logfiles to support.
maybe it's related to: http://forums.adafruit.com/viewtopic.php?f=22&p=265865 (Re: Possible DNS errors with CC3000)

"We've seen CC3000s hold onto the DNS server address longer than they should before. It seems to be some kind of glitch in the firmware. You can usually fix the problem by setting all the addresses statically, then telling the CC3000 to reboot and get a DHCP connection again."

**Comment by vicatcu** [comment] 2015-10-11 18:51
@PieterGit thanks for sending the logs. Definitely looks like something went crazy with the CC3000 DNS. I see you tried configuring Static IP address, and you got the same behavior in that case. Did you try setting it back to DHCP? You do can that with the command 'use dhcp' in config mode.

**Comment by PieterGit** [comment] 2015-10-11 19:23
it seems it doesn't make a difference to use dhcp or static ip. i'll revert back to dhcp by issueing "use dhcp"

**Comment by PieterGit** [comment] 2015-10-11 19:45
i tried to create a wrapper for getHostByName, but my c call-by-reference skills are lacking and the compiler prevented me from making it work. see my masterbranch at
https://github.com/PieterGit/AQEV2FW

Again: it's probably better for me to generate ideas and bug reports than to create code ;)

**Comment by PieterGit** [comment] 2015-10-11 19:48
my code seems on my master branch seems to works with dhcp and opmode offline with a NTP-client. i'm off for tonight, i'll check back later

**Comment by vicatcu** [comment] 2015-10-20 02:52
I'm closing this only because I don't have any way of reproducing it, we'll keep an eye out and try and address it if it comes up again.

**Closed as completed by vicatcu** 2015-10-20 02:52 UTC
